name: Update README with Images

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "nhattruong13112000@gmail.com"
          git config --global user.name "nhattruongNeoVim"

      - name: Update README
        run: |
          echo "## List Wallpapers" > README.md
          echo "> [!Important]" >> README.md
          echo "> These wallpapers are not mine. All credits goes to those who have created / photographed these nice wallpapers" >> README.md
          for file in $(ls wallpapers/*.{jpg,png} | sort); do
            filename=$(basename "$file")
            echo "### $filename" >> README.md
            echo "![]($file)" >> README.md
          done
          echo "> **Congratulations!** at this poit you have all the wallpapers that I've collected" >> README.md
          echo "> " >> README.md
          echo "> # (￣ y▽ ￣)╭ Ohohoho....." >> README.md
          git add README.md
          git commit -m "Update README with latest wallpapers" || true
          git push origin master

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
