name: Update README with Images

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Actions bot identity
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Update README
        run: |
          echo "## List Wallpapers" > README.md
          echo "> [!Important]" >> README.md
          echo "> These wallpapers are not mine. All credits goes to those who have created / photographed these nice wallpapers" >> README.md
          for file in $(ls wallpapers/*.{jpg,png} 2>/dev/null | sort); do
            filename=$(basename "$file")
            filename="${filename%.*}"
            echo "### $filename" >> README.md
            echo "![]($file)" >> README.md
          done
          echo "> **Congratulations!** at this point you have all the wallpapers that I've collected" >> README.md
          echo "> " >> README.md
          echo "> # (￣ y▽ ￣)╭ Ohohoho....." >> README.md

          git add README.md
          git commit -m "✅ Update README with latest wallpapers" || echo "No changes to commit"
          git push
