name: Update README with Images

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # - name: Set up Git
      #   run: |
      #     git config --global user.email "nhattruong13112000@gmail.com"
      #     git config --global user.name "nhattruongNeoVim"
      #
      - name: Update README
        run: |
          echo '## List Wallpapers\n' > README.md
          for file in wallpapers/*.{jpg,png}; do
            filename=$(basename "$file")
            echo "### filename" >> README.md
            echo "![]($file)" >> README.md
          done
          git add README.md
          git commit -m "Update README with latest wallpapers" || true
          git push origin master 

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
